# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasting', '0005_auto_20160905_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enclosure',
            options={'ordering': ('media_file', 'mime'), 'verbose_name': 'Enclosure', 'verbose_name_plural': 'Enclosures'},
        ),
        migrations.RemoveField(
            model_name='enclosure',
            name='url',
        ),
        migrations.AlterField(
            model_name='episode',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='published'),
        ),
    ]
