# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasting', '0007_auto_20160907_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube URL'),
        ),
    ]
