# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasting', '0008_episode_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Insert youtube embed url here, NOT regular url', null=True, verbose_name='Youtube URL'),
        ),
    ]
